security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Fournisseur d'utilisateurs
    providers:
        users_in_memory: { memory: null }
        users_from_database:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: users_from_database # Spécifiez le provider ici
            jwt: ~

    # Contrôle d'accès
    access_control:
        - { path: ^/api/users/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 4 # Valeur la plus basse pour bcrypt
                time_cost: 3 # Valeur la plus basse pour argon
                memory_cost: 10 # Valeur la plus basse pour argon
